export const doctorAppointments = [
  {
    id: 'appt-001',
    patientId: 'pt-1024',
    patientName: 'Aisha Tan',
    age: 28,
    gender: 'Female',
    service: 'General Consultation',
    reason: 'Fever and sore throat for 2 days',
    date: '04 Jun 2026',
    time: '10:30 AM',
    status: 'Pending',
    priority: 'Normal',
    symptomSummary: 'Fever, cough, fatigue',
    notes: 'Patient reported mild fatigue and reduced appetite.',
  },
  {
    id: 'appt-002',
    patientId: 'pt-1041',
    patientName: 'Daniel Wong',
    age: 54,
    gender: 'Male',
    service: 'Blood Pressure Follow-up',
    reason: 'Monthly blood pressure review',
    date: '04 Jun 2026',
    time: '10:45 AM',
    status: 'Confirmed',
    priority: 'High',
    symptomSummary: 'Headache, dizziness',
    notes: 'Review medication adherence and home readings.',
  },
  {
    id: 'appt-003',
    patientId: 'pt-1187',
    patientName: 'Nur Iman',
    age: 12,
    gender: 'Female',
    service: 'Vaccination',
    reason: 'Scheduled booster appointment',
    date: '04 Jun 2026',
    time: '11:15 AM',
    status: 'Completed',
    priority: 'Normal',
    symptomSummary: 'No active symptoms',
    notes: 'Observed after vaccination without issues.',
  },
  {
    id: 'appt-004',
    patientId: 'pt-1203',
    patientName: 'Michael Lee',
    age: 41,
    gender: 'Male',
    service: 'Health Screening Review',
    reason: 'Discuss screening outcome',
    date: '04 Jun 2026',
    time: '2:00 PM',
    status: 'Cancelled',
    priority: 'Normal',
    symptomSummary: 'No active symptoms',
    notes: 'Patient requested new date through reception.',
  },
]

export const doctorPatients = [
  {
    id: 'pt-1024',
    name: 'Aisha Tan',
    age: 28,
    gender: 'Female',
    phone: '+60 12 345 6789',
    email: 'aisha.tan@example.com',
    lastVisit: '18 Apr 2026',
    condition: 'Recurring fever',
    allergies: 'Penicillin',
    medication: 'Paracetamol as needed',
    emergencyContact: 'Hafiz Tan · +60 14 442 2190',
  },
  {
    id: 'pt-1041',
    name: 'Daniel Wong',
    age: 54,
    gender: 'Male',
    phone: '+60 16 882 1440',
    email: 'daniel.wong@example.com',
    lastVisit: '24 Apr 2026',
    condition: 'Hypertension follow-up',
    allergies: '-',
    medication: 'Amlodipine 5 mg',
    emergencyContact: 'Janice Wong · +60 12 889 1020',
  },
  {
    id: 'pt-1187',
    name: 'Nur Iman',
    age: 12,
    gender: 'Female',
    phone: '+60 19 770 4312',
    email: 'guardian.iman@example.com',
    lastVisit: '10 Mar 2026',
    condition: 'Vaccination schedule',
    allergies: '-',
    medication: '-',
    emergencyContact: 'Farah Iman · +60 17 224 7100',
  },
  {
    id: 'pt-1203',
    name: 'Michael Lee',
    age: 41,
    gender: 'Male',
    phone: '+60 11 2233 7744',
    email: 'michael.lee@example.com',
    lastVisit: '02 May 2026',
    condition: 'Health screening',
    allergies: 'Shellfish',
    medication: 'Cetirizine',
    emergencyContact: 'Rachel Lee · +60 18 332 9041',
  },
]

export const doctorPrescriptions = [
  {
    id: 'rx-001',
    patientId: 'pt-1024',
    patientName: 'Aisha Tan',
    medicine: 'Amoxicillin',
    strength: '500 mg',
    dosage: '1 capsule',
    frequency: '3 times daily',
    duration: '7 days',
    instructions: 'Take after food.',
    status: 'Active',
    issuedDate: '04 Jun 2026',
  },
  {
    id: 'rx-002',
    patientId: 'pt-1041',
    patientName: 'Daniel Wong',
    medicine: 'Amlodipine',
    strength: '5 mg',
    dosage: '1 tablet',
    frequency: 'Once daily',
    duration: '30 days',
    instructions: 'Monitor home blood pressure readings.',
    status: 'Active',
    issuedDate: '02 Jun 2026',
  },
  {
    id: 'rx-003',
    patientId: 'pt-1203',
    patientName: 'Michael Lee',
    medicine: 'Ibuprofen',
    strength: '400 mg',
    dosage: '1 tablet',
    frequency: 'Every 8 hours as needed',
    duration: '5 days',
    instructions: 'Use only if pain continues.',
    status: 'Completed',
    issuedDate: '25 May 2026',
  },
]

export const doctorNotifications = [
  {
    id: 'notif-001',
    type: 'Booking',
    title: 'New appointment request',
    body: 'Aisha Tan requested a same-day consultation for fever symptoms.',
    time: '10 min ago',
    status: 'Unread',
  },
  {
    id: 'notif-002',
    type: 'Follow-up',
    title: 'Prescription review reminder',
    body: 'Review Daniel Wong’s blood pressure medication during today’s follow-up.',
    time: '35 min ago',
    status: 'Unread',
  },
  {
    id: 'notif-003',
    type: 'Clinic',
    title: 'Appointment cancelled',
    body: 'Michael Lee cancelled the 2:00 PM health screening review.',
    time: '1 hr ago',
    status: 'Read',
  },
]

export const doctorDashboardNotes = [
  'Two pending bookings require confirmation before noon.',
  'One high-priority follow-up is scheduled in the current queue.',
  'Review active prescriptions that need refill instructions today.',
]
